"""State schema definitions for CompetitorIQ LangGraph multi-agent pipeline.

This module defines:
1. Pydantic models for structured plan generation (ResearchTask) and research output (Finding).
2. LangGraph state (CompetitorIQState) utilizing typed annotations and state reducers
   to ensure concurrent write-safety during parallel researcher execution.
"""

from __future__ import annotations

import operator
from enum import Enum
from typing import Annotated, Any, Optional
from typing_extensions import TypedDict
from pydantic import BaseModel, Field


class ResearchDomain(str, Enum):
    """Categorical domain breakdown for competitive intelligence."""

    PRICING_PACKAGING = "pricing_packaging"
    FEATURE_SET = "feature_set"
    CUSTOMER_SENTIMENT = "customer_sentiment"
    NEWS_FUNDING = "news_funding"
    POSITIONING_MESSAGING = "positioning_messaging"


class SourceItem(BaseModel):
    """Represents a verified external reference used to ground findings."""

    url: str = Field(description="Direct URL of the cited source.")
    title: str = Field(description="Page or document title.")
    snippet: str = Field(
        description="Relevant quoted or summarized excerpt extracted from the source."
    )


class ResearchTask(BaseModel):
    """A discrete, non-overlapping investigation unit generated by the Planner."""

    task_id: str = Field(
        description="Unique identifier for the task, e.g., 'task_pricing_01'."
    )
    domain: ResearchDomain = Field(
        description="Target research domain category."
    )
    description: str = Field(
        description="Explicit directive specifying what the researcher must investigate."
    )
    search_queries: list[str] = Field(
        default_factory=list,
        description="Pre-constructed, high-signal Tavily search queries.",
    )
    target_questions: list[str] = Field(
        default_factory=list,
        description="Specific hypotheses or questions the researcher must answer.",
    )


class Finding(BaseModel):
    """Structured evidence returned by a researcher for a specific ResearchTask."""

    task_id: str = Field(
        description="Identifier matching the corresponding ResearchTask.task_id."
    )
    domain: ResearchDomain = Field(
        description="Domain category for downstream report sectioning."
    )
    key_insights: list[str] = Field(
        description="Bulleted, high-level strategic takeaways."
    )
    detailed_summary: str = Field(
        description="Comprehensive narrative containing verified factual details."
    )
    raw_data_points: dict[str, Any] = Field(
        default_factory=dict,
        description="Structured key-value metrics (e.g. {'starter_price': '$29/mo'}).",
    )
    sources: list[SourceItem] = Field(
        default_factory=list,
        description="List of cited web sources grounding this finding.",
    )
    confidence_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Programmatically computed confidence level derived from corroborating source count (capped at 0.90).",
    )


class CompetitorIQState(TypedDict):
    """Root state schema for the CompetitorIQ LangGraph pipeline.

    Every field is explicitly documented with its read/write boundaries across
    graph nodes.
    """

    # Target company name
    # Reads: planner, writer
    # Writes: START (Graph initialization / User input)
    company_name: str

    # Optional primary homepage or product URL for the target company
    # Reads: planner, researcher (parallel workers)
    # Writes: START (Graph initialization / User input)
    company_url: Optional[str]

    # Structured list of research tasks generated by the Planner
    # Reads: human_review (checkpoint), dynamic_fanout_router, writer
    # Writes: planner (initial generation), human_review (manual user edits during interrupt)
    research_plan: list[ResearchTask]

    # Flag indicating whether the human operator approved the plan to proceed
    # Reads: plan_approval_router (conditional edge)
    # Writes: human_review (checkpoint approval / rejection)
    plan_approved: bool

    # Optional feedback provided by the human operator when requesting plan revision
    # Reads: planner (during re-planning loop)
    # Writes: human_review (checkpoint user feedback)
    user_feedback: Optional[str]

    # =========================================================================
    # CONCURRENT REDUCER EXPLANATION:
    # -------------------------------------------------------------------------
    # In LangGraph, when nodes run concurrently (such as parallel researchers
    # dispatched via the Send API), multiple workers will simultaneously return
    # state delta updates containing the "findings" key.
    #
    # Without an Annotated reducer, LangGraph treats state keys as last-write-wins
    # or raises an `InvalidUpdateError` due to conflicting concurrent writes to the
    # same state key within a single super-step.
    #
    # By annotating `findings` with `operator.add`, LangGraph treats state updates
    # as monoidal additions (list concatenation). Each parallel researcher yields
    # `{"findings": [finding]}`, and LangGraph safely appends each worker's output
    # into the shared `findings` list upon fan-in, preventing race conditions,
    # accidental overwrites, and state corruption.
    # =========================================================================
    # Reads: writer
    # Writes: researcher (multiple parallel instances via LangGraph Send API)
    findings: Annotated[list[Finding], operator.add]

    # The synthesized Markdown draft produced by the Writer awaiting review
    # Reads: draft_review (checkpoint), writer (regeneration)
    # Writes: writer
    report_draft: Optional[str]

    # Flag indicating whether the human operator approved the draft report
    # Reads: route_draft_approval (conditional edge)
    # Writes: draft_review (checkpoint approval / request changes)
    report_approved: bool

    # Optional feedback provided by human reviewer requesting changes to the draft report
    # Reads: writer (during report regeneration)
    # Writes: draft_review (checkpoint user feedback)
    report_feedback: Optional[str]

    # The final synthesized Markdown report produced by the Writer
    # Reads: API layer / client output
    # Writes: draft_review (upon final approval)
    final_report: Optional[str]

    # Non-fatal error logs aggregated across any node during pipeline execution
    # Reads: writer, API layer / monitoring
    # Writes: planner, researcher, writer
    errors: Annotated[list[str], operator.add]
